import {HOUR, MINUTE, DAY} from '@/constants/time';

export const OTP_RESEND_COOLDOWN = MINUTE;
export const OTP_LENGTH = 6;
export const OTP_EXPIRATION = MINUTE * 15;

export const FORGET_PASSWORD_CONSTANTS = {
    FORGET_PASSWORD_REQUEST_EXPIRATION: HOUR,
    FORGET_PASSWORD_LIMIT_WINDOW: DAY * 2,
    FORGET_PASSWORD_LIMIT_PER_WINDOW: 3,
    RESET_PASSWORD_LIMIT_WINDOW: DAY * 2,
    RESET_PASSWORD_LIMIT_PER_WINDOW: 1,
};
